# tasks file for s3cmd
- include: redhat.yml
  when: ansible_os_family == 'RedHat'
- include: debian.yml
  when: ansible_os_family == 'Debian'
- name: Get s3cmd pkg from github
  git:
    accept_hostkey: "yes"
    repo: "{{ s3cmd_repo }}"
    dest: "{{ s3cmd_dest }}"
    version: "{{ s3cmd_version }}"
- name: Run installation script
  command: sudo python setup.py install
  sudo_user: "{{ owner }}"
  args:
    chdir: "{{ s3cmd_dest }}"
    creates: "/usr/local/bin/s3cmd"
- name: Set config files a set location
  template:
    src: "s3cfg.j2"
    dest: "{{ s3cmd_cfg_path }}"
    mode: 0644
    owner: "{{ owner }}"
    group: "{{ group }}"
